# node model
FROM node:22-alpine


# Set working directory (inside the container make a folder named app and set it as working directory put everything inside it)
WORKDIR /app
# Copy package files
COPY package*.json .
# Copy application files first . saying take all files second . means put it in the same order in the container
COPY . .

# Install dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]